apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresdatabases.postgresdbadminoperator.github.io
spec:
  group: postgresdbadminoperator.github.io
  names:
    kind: PostgresDatabase
    plural: postgresdatabases
    singular: postgresdatabase
    shortNames:
      - pgdb
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                createReadOnlyUser:
                  type: boolean
                  default: false
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
