name: Release

on:
  push:
    branches:
      - main
    paths:
      - charts/**
      - src/**
      - Dockerfile

env:
  CHART_FILE: charts/postgres-db-admin-operator/Chart.yaml

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get chart version
        id: chart
        run: |
          echo "version=$(grep '^version:' ${{ env.CHART_FILE }} | awk '{print $2}')" >> $GITHUB_OUTPUT
          echo "chart_changed=$( git diff --name-only HEAD~1 HEAD | grep -q '${{ env.CHART_FILE }}' && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/nielstenboom/postgres-db-admin-operator:${{ steps.chart.outputs.version }}

      - name: Push Helm chart
        if: github.event_name != 'pull_request'
        uses: appany/helm-oci-chart-releaser@v0.5.0
        with:
          name: postgres-db-admin-operator
          repository: nielstenboom/charts
          tag: ${{ steps.chart.outputs.version }}
          path: charts/postgres-db-admin-operator
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        if: steps.chart.outputs.chart_changed == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.chart.outputs.version }}
          name: v${{ steps.chart.outputs.version }}
          generate_release_notes: true
