apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: operator
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PG_HOST
              value: {{ .Values.postgres.host | quote }}
            - name: PG_USER
              value: {{ .Values.postgres.user | quote }}
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.password.existingSecret }}
                  key: {{ .Values.postgres.password.secretKey }}
            - name: PG_PORT
              value: {{ .Values.postgres.port | quote }}
            - name: CLEANUP_ON_DELETE
              value: {{ .Values.cleanupOnDelete | quote }}
